services:
  app:
    image: avangardum/training_social_media
    restart: always
    ports:
      - 127.0.0.1:5002:80
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_SOCIAL_MEDIA_DB_ROOT_PASSWORD}