services:
  app:
    image: avangardum/training_social_media
    restart: always
    environment:
      DB_PASSWORD: ${TEST_SOCIAL_MEDIA_DB_ROOT_PASSWORD}
    ports:
      - 127.0.0.1:5002:80
    depends_on:
      - db
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_SOCIAL_MEDIA_DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: