name: Continuous integration

on:
  pull_request:
    branches: [ "main", "actions-test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Build
      run: docker build . -t ${{ vars.DOCKER_IMAGE_TAG }}
